name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Test PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, xml, ctype, json, bcmath
          coverage: xdebug
      
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      
      - name: Run tests
        run: composer test
      
      - name: Run tests with coverage
        if: matrix.php == '8.3'
        run: composer test:coverage

